// playgrounds/svelte-kit/src/routes/orpc-query.svelte
<script lang="ts">
  import { orpc } from '$lib/orpc';
  import { createInfiniteQuery } from '@tanstack/svelte-query';

  const query = createInfiniteQuery(
    orpc.planet.list.infiniteOptions({
      input: (cursor) => ({ cursor }),
      getNextPageParam: (lastPage) => (lastPage.at(-1)?.id ?? -1) + 1,
      initialPageParam: 0,
    })
  );
</script>

{#if $query.status === 'pending'}
  <p>Loading...</p>
{:else if $query.status === 'success'}
  <div>
    <h2>oRPC and TanStack Query | List Planets example</h2>
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Description</th>
          <th>Image</th>
        </tr>
      </thead>
      <tbody>
        {#each $query.data.pages as page}
          {#each page as planet}
            <tr>
              <td>{planet.id}</td>
              <td>{planet.name}</td>
              <td>{planet.description}</td>
              <td>{planet.imageUrl}</td>
            </tr>
          {/each}
        {/each}
      </tbody>
      <tfoot>
        <tr>
          <td colspan="4">
            <button
              on:click={() => $query.fetchNextPage()}
              disabled={!$query.hasNextPage}
            >
              Load more
            </button>
            <button on:click={() => $query.refetch()}> Refresh </button>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
{:else}
  <p>Something went wrong.</p>
{/if}

// playgrounds/solid-start/src/orpc-query.tsx
import { createInfiniteQuery } from '@tanstack/solid-query'
import { For } from 'solid-js'
import { orpc } from '~/lib/orpc'

export function ListPlanetsQuery() {
  const { data, refetch, fetchNextPage, hasNextPage, isLoading, status } = createInfiniteQuery(
    () => orpc.planet.list.infiniteOptions({
      input: cursor => ({ cursor }),
      getNextPageParam: lastPage => (lastPage.at(-1)?.id ?? -1) + 1,
      initialPageParam: 0,
    }),
  )

  if (status === 'pending') {
    return <p>Loading...</p>
  }

  if (status === 'error') {
    return (
      <p>
        Something went wrong.
      </p>
    )
  }

  return (
    <div>
      <h2>oRPC and Tanstack Query | List Planets example</h2>

      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Image</th>
          </tr>
        </thead>
        <tbody>
          <For each={data.pages}>
            {page => (
              <For each={page}>
                {planet => (
                  <tr>
                    <td>{planet.id}</td>
                    <td>{planet.name}</td>
                    <td>{planet.description}</td>
                    <td>{planet.imageUrl}</td>
                  </tr>
                )}
              </For>
            )}
          </For>
        </tbody>

        <tfoot>
          <tr>
            <td colSpan={4}>
              <button
                type="button"
                onClick={() => fetchNextPage()}
                disabled={!hasNextPage}
              >
                Load more
              </button>

              <button type="button" onClick={() => refetch()}>
                Refresh
              </button>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>

  )
}
