// playgrounds/svelte-kit/src/routes/+page.svelte
<script lang="ts">
  import { QueryClient, QueryClientProvider } from '@tanstack/svelte-query';
  import OrpcMutation from './orpc-mutation.svelte';
  import OrpcQuery from './orpc-query.svelte';

  const queryClient = new QueryClient();
</script>

<QueryClientProvider client={queryClient}>
  <div>
    <h1>ORPC Playground</h1>
    <p>
      You can visit the
      {' '}
      <a href="/scalar">Scalar API Reference</a>
      {' '}
      page.
    </p>
    <hr />
    <OrpcMutation />
    <hr />
    <OrpcQuery />
  </div>
</QueryClientProvider>

// playgrounds/tanstack-start/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router'
import { CreatePlanetMutationForm } from '~/components/orpc-mutation'
import { ListPlanetsQuery } from '~/components/orpc-query'

export const Route = createFileRoute('/')({
  component: RouteComponent,
})

function RouteComponent() {
  return (
    <div>
      <h1>ORPC Playground</h1>
      You can visit the
      {' '}
      <a href="/api">Redirect to Scalar API Reference</a>
      {' '}
      page.
      <hr />
      <CreatePlanetMutationForm />
      <hr />
      <ListPlanetsQuery />
    </div>
  )
}
